# Author Sourabh Aswal
# Senior Devops 


steps:

  # Build app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south2-docker.pkg.dev/realcoderzai/airepo/cloud-run:$COMMIT_SHA', '.']
    id: BUILD

  # Storage of the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south2-docker.pkg.dev/realcoderzai/airepo/cloud-run:$COMMIT_SHA']
    id: STORAGE

  # Deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'cloud-run',
          '--image', 'asia-south2-docker.pkg.dev/realcoderzai/airepo/cloud-run:$COMMIT_SHA',
          '--region', 'asia-south2',
          '--platform', 'managed',
          '--allow-unauthenticated']
    id: DEPLOY

options:
  logging: CLOUD_LOGGING_ONLY
 
